package guillaumebraibant.springsoapwshellow.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://springsoapwshellow.guillaumebraibant/soap", name = "sayHelloInterface")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SayHelloInterface {

    @WebMethod
    @WebResult(name = "response", targetNamespace = "", partName = "response")
    public java.lang.String sayHello(

        @WebParam(partName = "username", name = "username", targetNamespace = "")
        FullName username
    );
}
