
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package guillaumebraibant.springsoapwshellow.soap;

import java.util.logging.Logger;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;

import org.springframework.stereotype.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * Generated source version: 3.3.5
 *
 */

@javax.jws.WebService(
                      serviceName = "sayHelloService",
                      portName = "sayHelloInterface",
                      targetNamespace = "http://springsoapwshellow.guillaumebraibant/soap",
                      wsdlLocation = "classpath:soap/hellow.wsdl",
                      endpointInterface = "guillaumebraibant.springsoapwshellow.soap.SayHelloInterface")
public class SayHelloInterfaceImpl implements SayHelloInterface {

    private static final Logger LOG = Logger.getLogger(SayHelloInterfaceImpl.class.getName());

    /* (non-Javadoc)
     * @see guillaumebraibant.springsoapwshellow.soap.SayHelloInterface#sayHelloAsync(guillaumebraibant.springsoapwshellow.soap.FullName username)*
     */
    public Response<java.lang.String> sayHelloAsync(FullName username) {
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see guillaumebraibant.springsoapwshellow.soap.SayHelloInterface#sayHelloAsync(guillaumebraibant.springsoapwshellow.soap.FullName username, AsyncHandler<java.lang.String> asyncHandler)*
     */
    public Future<?> sayHelloAsync(FullName username, AsyncHandler<java.lang.String> asyncHandler) {
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see guillaumebraibant.springsoapwshellow.soap.SayHelloInterface#sayHello(guillaumebraibant.springsoapwshellow.soap.FullName username)*
     */
    public java.lang.String sayHello(FullName username) {
        LOG.info("Executing operation sayHello");
        System.out.println(username);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
