version: "3.3"

networks:
  sayhello:

volumes:
  logs:
  prometheus-data:

services:
      
  sayhello:
    build: .
    image: "${DOCKERHUB_REPO}:${SAYHELLO_BASE_TAG}-${IMAGES_VERSION}"
    container_name: sayhello
    volumes:
      - logs:/var/log
    ports:
      - "8080:8080"
    networks:
      - sayhello

  prometheus:
    build: ./monitoring/prometheus/compose
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    networks:
      - sayhello

  grafana:
    build: ./monitoring/grafana
    image: "${DOCKERHUB_REPO}:${GRAFANA_BASE_TAG}-${IMAGES_VERSION}"
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - sayhello
