version: "3.3"

networks:
  sayhello:

volumes:
  logs:
  prometheus-data:
  promtail-data:
  loki-data:

services:
      
  sayhello:
    build: .
    image: "${DOCKERHUB_REPO}:${SAYHELLO_BASE_TAG}-${IMAGES_VERSION}"
    container_name: sayhello
    volumes:
      - logs:/var/log
    ports:
      - "8080:8080"
    networks:
      - sayhello

  prometheus:
    build: ./monitoring/prometheus/compose
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    networks:
      - sayhello

  loki:
    image: grafana/loki:latest
    ports:
      - "3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/tmp/loki
    networks:
      - sayhello

  promtail:
    build: ./monitoring/promtail
    image: "${DOCKERHUB_REPO}:${PROMTAIL_BASE_TAG}-${IMAGES_VERSION}"
    command: -config.file=/etc/promtail/custom-config.yaml
    depends_on:
      - "sayhello"
    volumes:
      - logs:/var/log
      - promtail-data:/tmp
    networks:
      - sayhello

  grafana:
    build: ./monitoring/grafana
    image: "${DOCKERHUB_REPO}:${GRAFANA_BASE_TAG}-${IMAGES_VERSION}"
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - sayhello
