server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:

- job_name: logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: logs
      __path__: /var/log/*/*.log
