# Configuration du logger
# Les logs sont également sauvegardés dans un fichier local au container
logging.:
    path: /var/log/webservices
    file: /var/log/webservices/${HOSTNAME}-webservices.log
    pattern.file: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}) %clr(%-5p) %clr(${HOSTNAME}){faint} %clr(---){faint} %clr([%8.15t]) %clr(%-40.40logger{0}) %clr(:) %clr(%m){faint}%n"
    file.max-size: 5MB
    file.max-history: 3
