# Config file version
apiVersion: 1

# List of datasources that should be deleted from the database
deleteDatasources:

# Datasources to add to the database
datasources:

# Metrics datasource : Prometheus
-  access: proxy
   editable: false
   is_default: true
   name: prometheus
   org_id: 1
   type: prometheus
   url: http://prometheus:9090
   version: 1
