apiVersion: v1
kind: Service
metadata:
  name: hellow
  labels:
    app.kubernetes.io/name: hellow    
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: hellow
spec:
  clusterIP: None
  ports:
    - port : 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: hellow
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: hellow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellow
  labels:
    app.kubernetes.io/name: hellow
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: hellow
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: hellow
      app.kubernetes.io/component: app
      app.kubernetes.io/part-of: hellow
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hellow
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: hellow
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/hellow/admin/prometheus"
    spec:
      containers:
        - name: hellow
          image: "guillaumebraibant/k8s-ws-sboot-cxf:sayhello-1.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
