apiVersion: v1
kind: Service
metadata:
  name: hellow
  labels:
    app.kubernetes.io/name: hellow    
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: hellow
spec:
  type: clusterIP
  ports:
    - port : 8080
      targetPort: 8080
  selector:
    hellow: hellow-app-pods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellow
  labels:
    app.kubernetes.io/name: hellow
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: hellow
spec:
  replicas: 3
  selector:
    matchLabels:
      hellow: hellow-app-pods
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hellow
        app.kubernetes.io/component: pods
        app.kubernetes.io/part-of: hellow
        hellow: hellow-app-pods
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/hellow/admin/prometheus"
    spec:
      containers:
        - name: hellow
          image: "guillaumebraibant/k8s-ws-sboot-cxf:sayhello-1.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hellow/admin/health
              port: http
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 2
          startupProbe:
            httpGet:
              path: /hellow/admin/health
              port: http
            failureThreshold: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /hellow/admin/health
              port: http
            timeoutSeconds: 2
            periodSeconds: 1
            failureThreshold: 1
